### ISSUE TITLE
Uncaught ReferenceError: data is not defined

### ISSUE THREAD

**Issue by francycer** [openware/opendax#219]
Hello,

I was trying to setup OpenDAX and the html page at the given domain works but I'm getting an error as in the subject (both in Firefox and Chrome) for JS.

Do you have any pointer for me?

**Comment by alinetskyi** [comment]
> Hello,
> 
> I was trying to setup OpenDAX and the html page at the given domain works but I'm getting an error as in the subject (both in Firefox and Chrome) for JS.
> 
> Do you have any pointer for me?

Hi, it would be very helpful if you could provide screenshots, in any case there's an up to date video tutorial on how you can install opendax

https://www.youtube.com/watch?v=qLjl2csyVPw&ab_channel=MobiDAX

**Comment by patpat0** [comment]
Hey Guys
Got the same error on a new installation. ( stable and alpha)
As soon as the baseapp is added by hand, it works - but the redirects are wrong. Always points to /trading.

Screenshot Browser Console error
![opendax](https://user-images.githubusercontent.com/73696992/97698538-eee8e380-1aa8-11eb-9e2f-0c2450aac145.jpg)

**Comment by fasenderos** [comment]
It is not well documented in the [README](https://github.com/openware/baseapp#available-docker-build-args), but you have to build the base app docker image with the `BUILD_DOMAIN` argument.

Stop all the services with `rake service:all[stop]` if they are running.

Than go to your `home/app` directory and clone the [baseapp repo](https://github.com/openware/baseapp).
```
cd /home/app
git clone https://github.com/openware/baseapp.git
cd baseapp
```
Next build a baseapp docker image with the BUILD_DOMAIN argument. Replace `example.com` with your domain.

```
docker build -t frontend/baseapp:latest --build-arg BUILD_DOMAIN="example.com" .
```

Update OpenDAX config by setting the newly created image for the frontend in `app.yml`

```
### /home/app/opendax/config/app.yml

images:
  peatio: quay.io/openware/peatio:2.5.35
  barong: quay.io/openware/barong:2.5.14
  frontend: frontend/baseapp:latest
  tower: quay.io/openware/tower:2.5.21
  rango: quay.io/openware/rango:2.5.0
```

Now you can start all services with `rake service:all` and you should be able to see the frontend.
