### ISSUE TITLE
403 on the Api, vault issue?

### ISSUE THREAD

**Issue by dondre** [openware/opendax#315]
Trying to setup a local environment.

Did following:
docker + docker-compose + ruby environment
> bundle
> rake -t (shows all commands)
> rake service:all

Everything runs but half the services are in a reset loop.

The app settings are default and have '/etc/hosts' 127.0.0.1 www.app.local set.

When setting up compose I get this error 2.

```
Wait 5 second for backend
----- Checking Vault status -----
ERROR: 2
----- Vault is initialized -----
----- Unsealing Vault -----
----- Vault login -----
```

Logs in the matching service show this.

_/opt/vendor/bundle/ruby/2.6.0/gems/vault-0.15.0/lib/vault/client.rb:409:in `error': The Vault server at `http://vault:8200' responded with a 503. (Vault::HTTPServerError)
Any additional information the server supplied is shown below:

  * error performing token check: Vault is sealed_

On the frontend, I'm getting this error when attempting API calls

**Request Method: GET
Status Code: 403 Forbidden
http://www.app.local/api/v2/peatio/public/markets**

As per readme, I updated the **envoy.yaml.erv** file with cors options

```
cors:
  allow_origin:
  - "*"
  allow_methods: "PUT, GET, POST, DELETE, PATCH"
  allow_headers: "content-type, x-grpc-web, total, page, x-csrf-token"
  expose_headers: "total, page, x-csrf-token"
  allow_credentials: true
```

I'm hoping I'm missing a small thing, any advice?
