### ISSUE TITLE
Custom Front networking issue

### ISSUE THREAD

**Issue by mm580486** [openware/opendax#380]
Hi everybody
i cloned baseapp on my local pc and build an new image and pushed to regsitery server also i changed config/app.yml for my private frontend container, unfortunately when i recreate frontend container with service:frontend container return mysql connection error
```

 /go/pkg/mod/github.com/openware/pkg/database@v0.0.0-20210113145702-fb5cceb8f775/database.go:37
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused
2022/04/09 22:19:38 dial tcp 127.0.0.1:3306: connect: connection refused
```

app.yml
```

images:
  peatio: quay.io/openware/peatio:2.6.48
  barong: quay.io/openware/barong:2.6.44
  frontend: custom/frontend:CUSTOM_TAG
  tower: quay.io/openware/tower:2.6.66
  rango: quay.io/openware/rango:2.6.1
finex:
  enabled: false
  image: quay.io/openware/finex:2.6.39
  license_key: changeme
vendor:
  frontend: git@github.com:openware/baseapp.git
```

i checked container network and port everything is ok but i cant understand what is the problem

best regards
